import asyncio
import random
from typing import Dict, Any, List


class MockWhiteAgentSimulator:
    #Simulates white agent responses for green agent testing
    
    def __init__(self, success_rate: float = 0.7):
        self.success_rate = success_rate
        self.reset_count = 0
        print(f"[MockWhiteAgent] Initialized with {success_rate*100}% success rate")
    
    async def reset(self) -> bool:
        #Simulates white agent reset
        self.reset_count += 1
        print(f"[MockWhiteAgent] Reset #{self.reset_count}")
        await asyncio.sleep(0.1)
        return True
    
    async def execute_task(
        self, 
        task_id: str, 
        instruction: str, 
        tools: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        #Simulates white agent executing a task.
        
        print(f"[MockWhiteAgent] Executing task {task_id}: {instruction[:50]}...")
        
        await asyncio.sleep(0.5)
        
        is_success = random.random() < self.success_rate
        
        actions = self._generate_actions_from_instruction(instruction, tools)
        
        print(f"[MockWhiteAgent] Generated {len(actions)} actions")
        
        return {
            "jsonrpc": "2.0",
            "result": {
                "task_id": task_id,
                "status": "success" if is_success else "partial",
                "actions": actions,
                "message": f"Mock: Executed {len(actions)} actions",
            },
            "id": f"task_{task_id}"
        }
    
    def _generate_actions_from_instruction(
        self, 
        instruction: str, 
        tools: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        actions = []
        instruction_lower = instruction.lower()
        
        if "list" in instruction_lower or "show" in instruction_lower:
            actions.append({"name": "list_tickets", "kwargs": {"status": "todo"}})
        
        if "create" in instruction_lower or "new" in instruction_lower:
            actions.append({
                "name": "create_ticket",
                "kwargs": {
                    "title": "New task from instruction",
                    "description": "Generated by mock",
                    "priority": "medium"
                }
            })
        
        if "assign" in instruction_lower:
            actions.append({
                "name": "assign_user",
                "kwargs": {"ticket_id": "1", "user_id": "user1"}
            })
        
        if "update" in instruction_lower and "status" in instruction_lower:
            actions.append({
                "name": "update_status",
                "kwargs": {"ticket_id": "1", "status": "in_progress"}
            })
        
        if "priority" in instruction_lower:
            actions.append({
                "name": "update_priority",
                "kwargs": {"ticket_id": "1", "priority": "high"}
            })
        
        if "comment" in instruction_lower:
            actions.append({
                "name": "add_comment",
                "kwargs": {"ticket_id": "1", "comment": "Mock comment"}
            })
        
        # If no actions matched, use first available tool as fallback
        if not actions and tools:
            tool_name = tools[0].get("name", "list_tickets")
            actions.append({"name": tool_name, "kwargs": {}})
        
        return actions


async def test_mock():
    """Quick test function for the mock simulator."""
    mock = MockWhiteAgentSimulator(success_rate=0.8)
    await mock.reset()
    response = await mock.execute_task(
        "0",
        "Create a high priority ticket for user management",
        []
    )
    print(response)


if __name__ == "__main__":
    # Run test if executed directly
    asyncio.run(test_mock())
